### ISSUE TITLE
Which file I can start with?

### ISSUE THREAD

**Issue by Susan19900316** [EvilPsyCHo/TaskBot#5]
Thanks for you sharing!
The models in readme.md is very interesting. I am new is the domain of taskbot. I donnot know where to start. I want to learn you code for interest.
Looking forward you reply!

**Comment by EvilPsyCHo** [comment]
hi,  sorry for late reply.

I'm very busy recently,  maybe i will start this project in Dec.

Susan19900316 <notifications@github.com> 于2018年11月15日周四 下午8:11写道：
